# Generated by Django 5.2 on 2025-04-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_title_todo_task_alter_todo_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='Todo',
        ),
    ]
